# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-30 19:34
from __future__ import unicode_literals

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('url', models.CharField(default='#', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Please supply an image for this activity', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('position', models.DecimalField(decimal_places=1, default=0, help_text='Position partner on slide', max_digits=5)),
                ('url', models.CharField(blank=True, default='#', help_text='Link partner website', max_length=255, null=True, verbose_name='Url')),
                ('is_active', models.BooleanField(default=True, help_text='Is active this partner?')),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image of this partner', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a title for the slide', null=True, verbose_name='')),
                ('top_title', models.IntegerField(blank=True, default=100, help_text='Top position', null=True, verbose_name='Top')),
                ('left_title', models.IntegerField(blank=True, default=100, help_text='Left position', null=True, verbose_name='Left')),
                ('size_title', models.PositiveIntegerField(blank=True, default=100, help_text='Font size', null=True, verbose_name='Size')),
                ('color_title', colorfield.fields.ColorField(default='#FFF', max_length=18, verbose_name='Color')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Please supply a description for the slide', null=True, verbose_name='')),
                ('top_text', models.IntegerField(blank=True, default=300, help_text='Top position', null=True, verbose_name='Top')),
                ('left_text', models.IntegerField(blank=True, default=100, help_text='Left position', null=True, verbose_name='Left')),
                ('size_text', models.PositiveIntegerField(blank=True, default=50, help_text='Font size', null=True, verbose_name='Size')),
                ('color_text', colorfield.fields.ColorField(default='#FFF', max_length=18, verbose_name='Color')),
                ('show_button', models.BooleanField(default=True, help_text='Show button for this slide?', verbose_name='Show')),
                ('text_button', models.CharField(blank=True, default='Show More', max_length=255, null=True, verbose_name='Text')),
                ('url_button', models.CharField(blank=True, default='#', max_length=255, null=True, verbose_name='Url')),
                ('color_button', colorfield.fields.ColorField(default='#62e0c1', max_length=18, verbose_name='Color Background')),
                ('top_button', models.IntegerField(blank=True, default=500, help_text='Top position', null=True, verbose_name='Top')),
                ('left_button', models.IntegerField(blank=True, default=1000, help_text='Left position', null=True, verbose_name='Left')),
                ('is_active', models.BooleanField(default=True, help_text='Is active this slide?')),
                ('position', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Position Slide', max_digits=5, null=True)),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image for this slide. The recommended image size is 1920px width, and 670px height.', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SliderActive',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='app_slideractive', serialize=False, to='cms.CMSPlugin')),
                ('nav_buttons', models.BooleanField(default=True, help_text='Enable low controls?', verbose_name='Low Controls')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slider')),
            ],
            options={
                'verbose_name': 'Slider',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_profile', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('image', filer.fields.image.FilerImageField(help_text='Please supply an image for this member', on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.AddField(
            model_name='slide',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slider'),
        ),
    ]
