# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-30 19:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('url', models.CharField(default='#', max_length=255)),
                ('position', models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Position Project', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, help_text='Please supply an image for this project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_project', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
