# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-30 20:12
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('app', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please supply a name for this group', max_length=255)),
                ('email', models.EmailField(help_text='Please supply an email for this group', max_length=255)),
                ('description', models.TextField(help_text='Please supply a description for this group')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('url', models.CharField(default='#', max_length=255)),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, help_text='Please supply an image for this group', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, help_text='Please supply an image for this project', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
