# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-30 17:15
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190330_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, help_text='Please supply an image for this project', null=True, upload_to=''),
        ),
    ]
