# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-30 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190430_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, default=None, help_text='Please supply an image for this project', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
